name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Firebase Functions dependencies
        working-directory: ./functions
        run: npm install

      - name: Install Firebase Functions dependencies (axios)
        working-directory: ./functions
        run: npm install axios

      - name: Build React app
        run: |
          unset CI  # Unset the CI variable to prevent treating warnings as errors
          npm run build

      - name: Set up Google Cloud authentication
        env:
            GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
            echo "${GOOGLE_CREDENTIALS_JSON}" > $RUNNER_TEMP/credentials.json
            export GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/credentials.json
  
      - name: Deploy to Firebase Hosting and Functions
        env:
            GOOGLE_APPLICATION_CREDENTIALS: $RUNNER_TEMP/credentials.json
        run: |
            npm install -g firebase-tools
            firebase deploy --only hosting,functions