name: Firebase Deploy

on:
  push:
    branches:
      - main  # Adjust if you're using a different branch for deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Ensure this matches your local environment

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: |
          unset CI  # Unset the CI variable to prevent treating warnings as errors
          npm run build

      - name: Deploy to Firebase Hosting and Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting,functions
